[[header]]
:description: RISC-V Quality-of-Service (QoS) Identifiers (Ssqosid)
:company: RISC-V.org
:revdate: 1/2024
:revnumber: 1.0
:revremark: This document is in Stable state. Assume anything could still change, but limited change should be expected. See http://riscv.org/spec-state for details.
:url-riscv: http://riscv.org
:doctype: book
:preface-title: Preamble
:colophon:
:appendix-caption: Appendix
:imagesdir: images
:title-logo-image: image:risc-v_logo.svg[pdfwidth=3.25in,align=center]
// Settings:
:experimental:
:reproducible:
// needs to be changed? bug discussion started
//:WaveDromEditorApp: app/wavedrom-editor.app
:imagesoutdir: images
:bibtex-file: sqosid.bib
:bibtex-order: occurrence
:bibtex-style: ieee
:icons: font
:lang: en
:listing-caption: Listing
:sectnums:
:toc: left
:toclevels: 4
:source-highlighter: pygments
ifdef::backend-pdf[]
:source-highlighter: coderay
endif::[]
:data-uri:
:hide-uri-scheme:
:stem: latexmath
:footnote:
:xrefstyle: short

= RISC-V Quality-of-Service (QoS) Identifiers (Ssqosid)
Ved Shanbhogue

// Preamble
[WARNING]
.This document is in the link:http://riscv.org/spec-state[Stable state]
====
Assume anything could still change, but limited change should be expected.
This draft specification will change before being accepted as standard, so
implementations made to this draft specification will likely not conform to
the future standard.
====

[preface]
=== Copyright and license information
This specification is licensed under the Creative Commons
Attribution 4.0 International License (CC-BY 4.0). The full
license text is available at
https://creativecommons.org/licenses/by/4.0/.

Copyright 2023 by RISC-V International.

[preface]
=== Contributors
This RISC-V specification has been contributed to directly or indirectly by:
Aaron Durbin, Allen Baum, Greg Favor, Krste Asanović, Ved Shanbhogue

== Introduction
Quality of Service (QoS) is defined as the minimal end-to-end performance
guaranteed in advance by a service level agreement (SLA) to a workload.
Performance metrics might include measures such as instructions per cycle (IPC),
latency of service, etc.

When multiple workloads execute concurrently on modern processors—equipped with
large core counts, multiple cache hierarchies, and multiple memory
controllers—the performance of any given workload becomes less deterministic, or
even non-deterministic, due to shared resource contention cite:[PTCAMP].

To manage performance variability, system software needs resource allocation and
monitoring capabilities. These capabilities allow for the reservation of
resources like cache and bandwidth, thus meeting individual performance targets
while minimizing interference cite:[HERACLES]. For resource management, hardware
should provide monitoring features that allow system software to profile
workload resource consumption and allocate resources accordingly.

To facilitate this, the QoS Identifiers extension (Ssqosid) introduces the
`srmcfg` register, which configures a hart with two identifiers: a Resource
Control ID (`RCID`) and a Monitoring Counter ID (`MCID`). These identifiers
accompany each request issued by the hart to shared resource controllers.

Additional metadata, like the nature of the memory access and the ID of the
originating supervisor domain, can accompany `RCID` and `MCID`. Resource
controllers may use this metadata for differentiated service such as a different
capacity allocation for code storage vs. data storage. Resource controllers can
use this data for security policies such as not exposing statistics of one
security domain to another.

These identifiers are crucial for the proposed RISC-V Capacity and Bandwidth
Controller QoS Register Interface cite:[CBQRI], which provides methods for
setting resource usage limits and monitoring resource consumption. The `RCID`
controls resource allocations, while the `MCID` is used for tracking resource
usage.

include::sqosid.adoc[]
//the index must precede the bibliography
include::sqosid_biblio.adoc[]
