[[chapter2]]
== Quality-of-Service (QoS) Identifiers

The `sqoscfg` register is a 32-bit read/write register to configure a
Resource Control ID (`RCID`) and a Monitoring Counter ID (`MCID`). Both
`RCID` and `MCID` are WARL fields. The CSR number is TBD.

The `RCID` and `MCID` accompany each request made by the hart to shared
resource controllers. The `RCID` is used to determine the resource
allocations (e.g., cache occupancy limits, memory bandwidth limits, etc.) to
enforce. The `MCID` is used to identify a counter to monitor resource usage.

.`sqoscfg` register for RV32 and RV64

[wavedrom, , ]
....
{reg: [
  {bits: 12, name: 'RCID'},
  {bits:  4, name: 'WPRI'},
  {bits: 12, name: 'MCID'},
  {bits:  4, name: 'WPRI'},
], config:{lanes: 1, hspace:1024}}
....

The `RCID` and `MCID` configured in the `sqoscfg` CSR apply to all privilege
modes cite:[PRIV] of software execution on that hart. 

[NOTE]
====
A reset value of 0 is suggested for the `RCID` field matching resource
controllers' default behavior of associating all capacity with `RCID=0`. The
`MCID` reset value does not affect functionality and may be
implementation-defined.

Typically, fewer bits are allocated for `RCID` (e.g., to support tens of RCIDs)
than for `MCID` (e.g., to support hundreds of MCIDs). A common `RCID` is usually
used to group apps or VMs, pooling resource allocations to meet collective SLAs.
If an SLA breach occurs, unique MCIDs enable granular monitoring, aiding
decisions on resource adjustment, associating a different `RCID` with a subset
of members, or migrating members to other machines. The larger pool of MCIDs
speeds up this analysis.

The `RCID` and `MCID` in `sqoscfg` apply across all privilege levels on the hart.
Typically, higher-privilege modes don't modify `sqoscfg`, as they often serve
lower-privileged tasks. If differentiation is needed, higher privilege code can
update `sqoscfg` and restore it before returning to a lower privilege level.

In VM environments, hypervisors usually manage resource allocations, keeping
the Guest OS out of QoS flows. If needed, the hypervisor can virtualize
`sqoscfg` CSR for a VM using the virtual-instruction exceptions triggered upon
Guest access. If the direct selection of `RCID` and `MCID` by the VM becomes
common and emulation overhead is an issue, future extensions may allow VS-mode
to use a selector for a hypervisor-configured set of CSRs holding `RCID` and
`MCID` values designated for that Guest OS use.

During context switches, the supervisor may choose to execute with the `sqoscfg`
of the outgoing context to attribute the execution to it. Prior to restoring
the new context, it switches to the new VM's `sqoscfg`. The supervisor can also
use a separate configuration for execution not to be attributed to either
contexts.
====
